sudo: false

language: python

python:
  - "3.4"

env:
  - TOXENV=py27-django17,py33-django17
  - TOXENV=py27-django18,py33-django18
  - TOXENV=py27-django19,py34-django19

install:
    - pip install tox pip -U

script:
    - tox

branches:
  only:
    - master
